### ISSUE TITLE
Support for .cshtml

### ISSUE THREAD

**Issue by ivarlovlie** [MairwunNx/The-Premium-Dark-Bug-Tracker#1]
Great work on this theme!

It doesn't look like .cshtml files are themed, is this by design?

![image](https://user-images.githubusercontent.com/38570165/153871606-d1fc931a-bbac-4722-ba6a-2e3630d2bce7.png)

**Comment by MairwunNx** [comment]
Thanks for reporting this issue! I'll try to fix it as soon I can. I'll notify you when this will done.

**Comment by MairwunNx** [comment]
@ivarlovlie I fixed that and test with this code

![image](https://user-images.githubusercontent.com/39625750/153922929-5fe84c02-697a-41cc-8336-b8e58ecc0890.png)

Still some colors wrong for classical `cshtml` highlight?

This changed will deployed in `1.2.0` version with support `cshtml` highlight. 

Probably JetBrains will accept update in next morning (15 feb)

**Comment by MairwunNx** [comment]
Close this please if your issue resolved or provide additional details to fix

As an apology for the current situation, if you really liked this theme, I give you an 80% discount on the purchase of the theme, it's valid until 17 feb (If you haven't received it, please email me.) 

[Coupon for 80% discount](https://github.com/MairwunNx/The-Premium-Dark-Bug-Tracker/files/8063116/download.1.pdf) (link to pdf file)

**Comment by ivarlovlie** [comment]
Looks good! Thanks for the quick turnaround, and thank you for the discount but i have already purchased the theme.
