### ISSUE TITLE
Plugin license can't buy now.

### ISSUE THREAD

**Issue by gerryhjs** [MairwunNx/The-Premium-Dark-Bug-Tracker#2]
There is no pricing page in plugin website.

**Comment by MairwunNx** [comment]
@gerryhjs Sorry for this situation, JetBrains has denied any licenses from Russia plugins if you wanna this theme, I can drop there is for free

**Comment by gerryhjs** [comment]
@MairwunNx Never mind. I saw you mark it deprecated yet. I am also a plugin developer, I just wanted to remind you if you forgot to enable payment when I found it.
